name: hoyoverse_gacha_import_tools
description: "A new Flutter project."
publish_to: 'none'
version: 2.0.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  http: ^1.3.0
  process_run: ^1.2.3
  url_launcher: ^6.2.4
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
